/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) multi_car_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s1[159] = {12, 12, 0, 12, 24, 36, 48, 60, 72, 84, 96, 108, 120, 132, 144, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s2[81] = {12, 6, 0, 12, 24, 36, 48, 60, 72, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s3[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s4[266] = {262, 1, 0, 262, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261};

/* multi_car_expl_vde_forw:(i0[12],i1[12x12],i2[12x6],i3[6],i4[262])->(o0[12],o1[12x12],o2[12x6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][3] : 0;
  a1=arg[0]? arg[0][2] : 0;
  a2=cos(a1);
  a3=(a0*a2);
  if (res[0]!=0) res[0][0]=a3;
  a3=sin(a1);
  a4=(a0*a3);
  if (res[0]!=0) res[0][1]=a4;
  a4=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][2]=a4;
  a5=5.;
  a6=arg[3]? arg[3][0] : 0;
  a6=(a6-a0);
  a6=(a5*a6);
  if (res[0]!=0) res[0][3]=a6;
  a6=arg[3]? arg[3][1] : 0;
  a6=(a6-a4);
  a6=(a5*a6);
  if (res[0]!=0) res[0][4]=a6;
  a6=arg[3]? arg[3][2] : 0;
  if (res[0]!=0) res[0][5]=a6;
  a6=arg[0]? arg[0][9] : 0;
  a4=arg[0]? arg[0][8] : 0;
  a7=cos(a4);
  a8=(a6*a7);
  if (res[0]!=0) res[0][6]=a8;
  a8=sin(a4);
  a9=(a6*a8);
  if (res[0]!=0) res[0][7]=a9;
  a9=arg[0]? arg[0][10] : 0;
  if (res[0]!=0) res[0][8]=a9;
  a10=arg[3]? arg[3][3] : 0;
  a10=(a10-a6);
  a10=(a5*a10);
  if (res[0]!=0) res[0][9]=a10;
  a10=arg[3]? arg[3][4] : 0;
  a10=(a10-a9);
  a10=(a5*a10);
  if (res[0]!=0) res[0][10]=a10;
  a10=arg[3]? arg[3][5] : 0;
  if (res[0]!=0) res[0][11]=a10;
  a10=arg[1]? arg[1][3] : 0;
  a9=(a2*a10);
  a11=sin(a1);
  a12=arg[1]? arg[1][2] : 0;
  a13=(a11*a12);
  a13=(a0*a13);
  a9=(a9-a13);
  if (res[1]!=0) res[1][0]=a9;
  a9=(a3*a10);
  a13=cos(a1);
  a12=(a13*a12);
  a12=(a0*a12);
  a9=(a9+a12);
  if (res[1]!=0) res[1][1]=a9;
  a9=arg[1]? arg[1][4] : 0;
  if (res[1]!=0) res[1][2]=a9;
  a10=(a5*a10);
  a10=(-a10);
  if (res[1]!=0) res[1][3]=a10;
  a9=(a5*a9);
  a9=(-a9);
  if (res[1]!=0) res[1][4]=a9;
  a9=0.;
  if (res[1]!=0) res[1][5]=a9;
  a10=arg[1]? arg[1][9] : 0;
  a12=(a7*a10);
  a14=sin(a4);
  a15=arg[1]? arg[1][8] : 0;
  a16=(a14*a15);
  a16=(a6*a16);
  a12=(a12-a16);
  if (res[1]!=0) res[1][6]=a12;
  a12=(a8*a10);
  a16=cos(a4);
  a15=(a16*a15);
  a15=(a6*a15);
  a12=(a12+a15);
  if (res[1]!=0) res[1][7]=a12;
  a12=arg[1]? arg[1][10] : 0;
  if (res[1]!=0) res[1][8]=a12;
  a10=(a5*a10);
  a10=(-a10);
  if (res[1]!=0) res[1][9]=a10;
  a12=(a5*a12);
  a12=(-a12);
  if (res[1]!=0) res[1][10]=a12;
  if (res[1]!=0) res[1][11]=a9;
  a12=arg[1]? arg[1][15] : 0;
  a10=(a2*a12);
  a15=arg[1]? arg[1][14] : 0;
  a17=(a11*a15);
  a17=(a0*a17);
  a10=(a10-a17);
  if (res[1]!=0) res[1][12]=a10;
  a10=(a3*a12);
  a15=(a13*a15);
  a15=(a0*a15);
  a10=(a10+a15);
  if (res[1]!=0) res[1][13]=a10;
  a10=arg[1]? arg[1][16] : 0;
  if (res[1]!=0) res[1][14]=a10;
  a12=(a5*a12);
  a12=(-a12);
  if (res[1]!=0) res[1][15]=a12;
  a10=(a5*a10);
  a10=(-a10);
  if (res[1]!=0) res[1][16]=a10;
  if (res[1]!=0) res[1][17]=a9;
  a10=arg[1]? arg[1][21] : 0;
  a12=(a7*a10);
  a15=arg[1]? arg[1][20] : 0;
  a17=(a14*a15);
  a17=(a6*a17);
  a12=(a12-a17);
  if (res[1]!=0) res[1][18]=a12;
  a12=(a8*a10);
  a15=(a16*a15);
  a15=(a6*a15);
  a12=(a12+a15);
  if (res[1]!=0) res[1][19]=a12;
  a12=arg[1]? arg[1][22] : 0;
  if (res[1]!=0) res[1][20]=a12;
  a10=(a5*a10);
  a10=(-a10);
  if (res[1]!=0) res[1][21]=a10;
  a12=(a5*a12);
  a12=(-a12);
  if (res[1]!=0) res[1][22]=a12;
  if (res[1]!=0) res[1][23]=a9;
  a12=arg[1]? arg[1][27] : 0;
  a10=(a2*a12);
  a15=arg[1]? arg[1][26] : 0;
  a17=(a11*a15);
  a17=(a0*a17);
  a10=(a10-a17);
  if (res[1]!=0) res[1][24]=a10;
  a10=(a3*a12);
  a15=(a13*a15);
  a15=(a0*a15);
  a10=(a10+a15);
  if (res[1]!=0) res[1][25]=a10;
  a10=arg[1]? arg[1][28] : 0;
  if (res[1]!=0) res[1][26]=a10;
  a12=(a5*a12);
  a12=(-a12);
  if (res[1]!=0) res[1][27]=a12;
  a10=(a5*a10);
  a10=(-a10);
  if (res[1]!=0) res[1][28]=a10;
  if (res[1]!=0) res[1][29]=a9;
  a10=arg[1]? arg[1][33] : 0;
  a12=(a7*a10);
  a15=arg[1]? arg[1][32] : 0;
  a17=(a14*a15);
  a17=(a6*a17);
  a12=(a12-a17);
  if (res[1]!=0) res[1][30]=a12;
  a12=(a8*a10);
  a15=(a16*a15);
  a15=(a6*a15);
  a12=(a12+a15);
  if (res[1]!=0) res[1][31]=a12;
  a12=arg[1]? arg[1][34] : 0;
  if (res[1]!=0) res[1][32]=a12;
  a10=(a5*a10);
  a10=(-a10);
  if (res[1]!=0) res[1][33]=a10;
  a12=(a5*a12);
  a12=(-a12);
  if (res[1]!=0) res[1][34]=a12;
  if (res[1]!=0) res[1][35]=a9;
  a12=arg[1]? arg[1][39] : 0;
  a10=(a2*a12);
  a15=arg[1]? arg[1][38] : 0;
  a17=(a11*a15);
  a17=(a0*a17);
  a10=(a10-a17);
  if (res[1]!=0) res[1][36]=a10;
  a10=(a3*a12);
  a15=(a13*a15);
  a15=(a0*a15);
  a10=(a10+a15);
  if (res[1]!=0) res[1][37]=a10;
  a10=arg[1]? arg[1][40] : 0;
  if (res[1]!=0) res[1][38]=a10;
  a12=(a5*a12);
  a12=(-a12);
  if (res[1]!=0) res[1][39]=a12;
  a10=(a5*a10);
  a10=(-a10);
  if (res[1]!=0) res[1][40]=a10;
  if (res[1]!=0) res[1][41]=a9;
  a10=arg[1]? arg[1][45] : 0;
  a12=(a7*a10);
  a15=arg[1]? arg[1][44] : 0;
  a17=(a14*a15);
  a17=(a6*a17);
  a12=(a12-a17);
  if (res[1]!=0) res[1][42]=a12;
  a12=(a8*a10);
  a15=(a16*a15);
  a15=(a6*a15);
  a12=(a12+a15);
  if (res[1]!=0) res[1][43]=a12;
  a12=arg[1]? arg[1][46] : 0;
  if (res[1]!=0) res[1][44]=a12;
  a10=(a5*a10);
  a10=(-a10);
  if (res[1]!=0) res[1][45]=a10;
  a12=(a5*a12);
  a12=(-a12);
  if (res[1]!=0) res[1][46]=a12;
  if (res[1]!=0) res[1][47]=a9;
  a12=arg[1]? arg[1][51] : 0;
  a10=(a2*a12);
  a15=arg[1]? arg[1][50] : 0;
  a17=(a11*a15);
  a17=(a0*a17);
  a10=(a10-a17);
  if (res[1]!=0) res[1][48]=a10;
  a10=(a3*a12);
  a15=(a13*a15);
  a15=(a0*a15);
  a10=(a10+a15);
  if (res[1]!=0) res[1][49]=a10;
  a10=arg[1]? arg[1][52] : 0;
  if (res[1]!=0) res[1][50]=a10;
  a12=(a5*a12);
  a12=(-a12);
  if (res[1]!=0) res[1][51]=a12;
  a10=(a5*a10);
  a10=(-a10);
  if (res[1]!=0) res[1][52]=a10;
  if (res[1]!=0) res[1][53]=a9;
  a10=arg[1]? arg[1][57] : 0;
  a12=(a7*a10);
  a15=arg[1]? arg[1][56] : 0;
  a17=(a14*a15);
  a17=(a6*a17);
  a12=(a12-a17);
  if (res[1]!=0) res[1][54]=a12;
  a12=(a8*a10);
  a15=(a16*a15);
  a15=(a6*a15);
  a12=(a12+a15);
  if (res[1]!=0) res[1][55]=a12;
  a12=arg[1]? arg[1][58] : 0;
  if (res[1]!=0) res[1][56]=a12;
  a10=(a5*a10);
  a10=(-a10);
  if (res[1]!=0) res[1][57]=a10;
  a12=(a5*a12);
  a12=(-a12);
  if (res[1]!=0) res[1][58]=a12;
  if (res[1]!=0) res[1][59]=a9;
  a12=arg[1]? arg[1][63] : 0;
  a10=(a2*a12);
  a15=arg[1]? arg[1][62] : 0;
  a17=(a11*a15);
  a17=(a0*a17);
  a10=(a10-a17);
  if (res[1]!=0) res[1][60]=a10;
  a10=(a3*a12);
  a15=(a13*a15);
  a15=(a0*a15);
  a10=(a10+a15);
  if (res[1]!=0) res[1][61]=a10;
  a10=arg[1]? arg[1][64] : 0;
  if (res[1]!=0) res[1][62]=a10;
  a12=(a5*a12);
  a12=(-a12);
  if (res[1]!=0) res[1][63]=a12;
  a10=(a5*a10);
  a10=(-a10);
  if (res[1]!=0) res[1][64]=a10;
  if (res[1]!=0) res[1][65]=a9;
  a10=arg[1]? arg[1][69] : 0;
  a12=(a7*a10);
  a15=arg[1]? arg[1][68] : 0;
  a17=(a14*a15);
  a17=(a6*a17);
  a12=(a12-a17);
  if (res[1]!=0) res[1][66]=a12;
  a12=(a8*a10);
  a15=(a16*a15);
  a15=(a6*a15);
  a12=(a12+a15);
  if (res[1]!=0) res[1][67]=a12;
  a12=arg[1]? arg[1][70] : 0;
  if (res[1]!=0) res[1][68]=a12;
  a10=(a5*a10);
  a10=(-a10);
  if (res[1]!=0) res[1][69]=a10;
  a12=(a5*a12);
  a12=(-a12);
  if (res[1]!=0) res[1][70]=a12;
  if (res[1]!=0) res[1][71]=a9;
  a12=arg[1]? arg[1][75] : 0;
  a10=(a2*a12);
  a15=arg[1]? arg[1][74] : 0;
  a17=(a11*a15);
  a17=(a0*a17);
  a10=(a10-a17);
  if (res[1]!=0) res[1][72]=a10;
  a10=(a3*a12);
  a15=(a13*a15);
  a15=(a0*a15);
  a10=(a10+a15);
  if (res[1]!=0) res[1][73]=a10;
  a10=arg[1]? arg[1][76] : 0;
  if (res[1]!=0) res[1][74]=a10;
  a12=(a5*a12);
  a12=(-a12);
  if (res[1]!=0) res[1][75]=a12;
  a10=(a5*a10);
  a10=(-a10);
  if (res[1]!=0) res[1][76]=a10;
  if (res[1]!=0) res[1][77]=a9;
  a10=arg[1]? arg[1][81] : 0;
  a12=(a7*a10);
  a15=arg[1]? arg[1][80] : 0;
  a17=(a14*a15);
  a17=(a6*a17);
  a12=(a12-a17);
  if (res[1]!=0) res[1][78]=a12;
  a12=(a8*a10);
  a15=(a16*a15);
  a15=(a6*a15);
  a12=(a12+a15);
  if (res[1]!=0) res[1][79]=a12;
  a12=arg[1]? arg[1][82] : 0;
  if (res[1]!=0) res[1][80]=a12;
  a10=(a5*a10);
  a10=(-a10);
  if (res[1]!=0) res[1][81]=a10;
  a12=(a5*a12);
  a12=(-a12);
  if (res[1]!=0) res[1][82]=a12;
  if (res[1]!=0) res[1][83]=a9;
  a12=arg[1]? arg[1][87] : 0;
  a10=(a2*a12);
  a15=arg[1]? arg[1][86] : 0;
  a17=(a11*a15);
  a17=(a0*a17);
  a10=(a10-a17);
  if (res[1]!=0) res[1][84]=a10;
  a10=(a3*a12);
  a15=(a13*a15);
  a15=(a0*a15);
  a10=(a10+a15);
  if (res[1]!=0) res[1][85]=a10;
  a10=arg[1]? arg[1][88] : 0;
  if (res[1]!=0) res[1][86]=a10;
  a12=(a5*a12);
  a12=(-a12);
  if (res[1]!=0) res[1][87]=a12;
  a10=(a5*a10);
  a10=(-a10);
  if (res[1]!=0) res[1][88]=a10;
  if (res[1]!=0) res[1][89]=a9;
  a10=arg[1]? arg[1][93] : 0;
  a12=(a7*a10);
  a15=arg[1]? arg[1][92] : 0;
  a17=(a14*a15);
  a17=(a6*a17);
  a12=(a12-a17);
  if (res[1]!=0) res[1][90]=a12;
  a12=(a8*a10);
  a15=(a16*a15);
  a15=(a6*a15);
  a12=(a12+a15);
  if (res[1]!=0) res[1][91]=a12;
  a12=arg[1]? arg[1][94] : 0;
  if (res[1]!=0) res[1][92]=a12;
  a10=(a5*a10);
  a10=(-a10);
  if (res[1]!=0) res[1][93]=a10;
  a12=(a5*a12);
  a12=(-a12);
  if (res[1]!=0) res[1][94]=a12;
  if (res[1]!=0) res[1][95]=a9;
  a12=arg[1]? arg[1][99] : 0;
  a10=(a2*a12);
  a15=arg[1]? arg[1][98] : 0;
  a17=(a11*a15);
  a17=(a0*a17);
  a10=(a10-a17);
  if (res[1]!=0) res[1][96]=a10;
  a10=(a3*a12);
  a15=(a13*a15);
  a15=(a0*a15);
  a10=(a10+a15);
  if (res[1]!=0) res[1][97]=a10;
  a10=arg[1]? arg[1][100] : 0;
  if (res[1]!=0) res[1][98]=a10;
  a12=(a5*a12);
  a12=(-a12);
  if (res[1]!=0) res[1][99]=a12;
  a10=(a5*a10);
  a10=(-a10);
  if (res[1]!=0) res[1][100]=a10;
  if (res[1]!=0) res[1][101]=a9;
  a10=arg[1]? arg[1][105] : 0;
  a12=(a7*a10);
  a15=arg[1]? arg[1][104] : 0;
  a17=(a14*a15);
  a17=(a6*a17);
  a12=(a12-a17);
  if (res[1]!=0) res[1][102]=a12;
  a12=(a8*a10);
  a15=(a16*a15);
  a15=(a6*a15);
  a12=(a12+a15);
  if (res[1]!=0) res[1][103]=a12;
  a12=arg[1]? arg[1][106] : 0;
  if (res[1]!=0) res[1][104]=a12;
  a10=(a5*a10);
  a10=(-a10);
  if (res[1]!=0) res[1][105]=a10;
  a12=(a5*a12);
  a12=(-a12);
  if (res[1]!=0) res[1][106]=a12;
  if (res[1]!=0) res[1][107]=a9;
  a12=arg[1]? arg[1][111] : 0;
  a10=(a2*a12);
  a15=arg[1]? arg[1][110] : 0;
  a17=(a11*a15);
  a17=(a0*a17);
  a10=(a10-a17);
  if (res[1]!=0) res[1][108]=a10;
  a10=(a3*a12);
  a15=(a13*a15);
  a15=(a0*a15);
  a10=(a10+a15);
  if (res[1]!=0) res[1][109]=a10;
  a10=arg[1]? arg[1][112] : 0;
  if (res[1]!=0) res[1][110]=a10;
  a12=(a5*a12);
  a12=(-a12);
  if (res[1]!=0) res[1][111]=a12;
  a10=(a5*a10);
  a10=(-a10);
  if (res[1]!=0) res[1][112]=a10;
  if (res[1]!=0) res[1][113]=a9;
  a10=arg[1]? arg[1][117] : 0;
  a12=(a7*a10);
  a15=arg[1]? arg[1][116] : 0;
  a17=(a14*a15);
  a17=(a6*a17);
  a12=(a12-a17);
  if (res[1]!=0) res[1][114]=a12;
  a12=(a8*a10);
  a15=(a16*a15);
  a15=(a6*a15);
  a12=(a12+a15);
  if (res[1]!=0) res[1][115]=a12;
  a12=arg[1]? arg[1][118] : 0;
  if (res[1]!=0) res[1][116]=a12;
  a10=(a5*a10);
  a10=(-a10);
  if (res[1]!=0) res[1][117]=a10;
  a12=(a5*a12);
  a12=(-a12);
  if (res[1]!=0) res[1][118]=a12;
  if (res[1]!=0) res[1][119]=a9;
  a12=arg[1]? arg[1][123] : 0;
  a10=(a2*a12);
  a15=arg[1]? arg[1][122] : 0;
  a17=(a11*a15);
  a17=(a0*a17);
  a10=(a10-a17);
  if (res[1]!=0) res[1][120]=a10;
  a10=(a3*a12);
  a15=(a13*a15);
  a15=(a0*a15);
  a10=(a10+a15);
  if (res[1]!=0) res[1][121]=a10;
  a10=arg[1]? arg[1][124] : 0;
  if (res[1]!=0) res[1][122]=a10;
  a12=(a5*a12);
  a12=(-a12);
  if (res[1]!=0) res[1][123]=a12;
  a10=(a5*a10);
  a10=(-a10);
  if (res[1]!=0) res[1][124]=a10;
  if (res[1]!=0) res[1][125]=a9;
  a10=arg[1]? arg[1][129] : 0;
  a12=(a7*a10);
  a15=arg[1]? arg[1][128] : 0;
  a17=(a14*a15);
  a17=(a6*a17);
  a12=(a12-a17);
  if (res[1]!=0) res[1][126]=a12;
  a12=(a8*a10);
  a15=(a16*a15);
  a15=(a6*a15);
  a12=(a12+a15);
  if (res[1]!=0) res[1][127]=a12;
  a12=arg[1]? arg[1][130] : 0;
  if (res[1]!=0) res[1][128]=a12;
  a10=(a5*a10);
  a10=(-a10);
  if (res[1]!=0) res[1][129]=a10;
  a12=(a5*a12);
  a12=(-a12);
  if (res[1]!=0) res[1][130]=a12;
  if (res[1]!=0) res[1][131]=a9;
  a12=arg[1]? arg[1][135] : 0;
  a10=(a2*a12);
  a15=arg[1]? arg[1][134] : 0;
  a11=(a11*a15);
  a11=(a0*a11);
  a10=(a10-a11);
  if (res[1]!=0) res[1][132]=a10;
  a10=(a3*a12);
  a13=(a13*a15);
  a13=(a0*a13);
  a10=(a10+a13);
  if (res[1]!=0) res[1][133]=a10;
  a10=arg[1]? arg[1][136] : 0;
  if (res[1]!=0) res[1][134]=a10;
  a12=(a5*a12);
  a12=(-a12);
  if (res[1]!=0) res[1][135]=a12;
  a10=(a5*a10);
  a10=(-a10);
  if (res[1]!=0) res[1][136]=a10;
  if (res[1]!=0) res[1][137]=a9;
  a10=arg[1]? arg[1][141] : 0;
  a12=(a7*a10);
  a13=arg[1]? arg[1][140] : 0;
  a14=(a14*a13);
  a14=(a6*a14);
  a12=(a12-a14);
  if (res[1]!=0) res[1][138]=a12;
  a12=(a8*a10);
  a16=(a16*a13);
  a16=(a6*a16);
  a12=(a12+a16);
  if (res[1]!=0) res[1][139]=a12;
  a12=arg[1]? arg[1][142] : 0;
  if (res[1]!=0) res[1][140]=a12;
  a10=(a5*a10);
  a10=(-a10);
  if (res[1]!=0) res[1][141]=a10;
  a12=(a5*a12);
  a12=(-a12);
  if (res[1]!=0) res[1][142]=a12;
  if (res[1]!=0) res[1][143]=a9;
  a12=arg[2]? arg[2][3] : 0;
  a10=(a2*a12);
  a16=sin(a1);
  a13=arg[2]? arg[2][2] : 0;
  a14=(a16*a13);
  a14=(a0*a14);
  a10=(a10-a14);
  if (res[2]!=0) res[2][0]=a10;
  a10=(a3*a12);
  a1=cos(a1);
  a13=(a1*a13);
  a13=(a0*a13);
  a10=(a10+a13);
  if (res[2]!=0) res[2][1]=a10;
  a10=arg[2]? arg[2][4] : 0;
  if (res[2]!=0) res[2][2]=a10;
  a12=(a5*a12);
  a12=(a5-a12);
  if (res[2]!=0) res[2][3]=a12;
  a10=(a5*a10);
  a10=(-a10);
  if (res[2]!=0) res[2][4]=a10;
  if (res[2]!=0) res[2][5]=a9;
  a10=arg[2]? arg[2][9] : 0;
  a12=(a7*a10);
  a13=sin(a4);
  a14=arg[2]? arg[2][8] : 0;
  a15=(a13*a14);
  a15=(a6*a15);
  a12=(a12-a15);
  if (res[2]!=0) res[2][6]=a12;
  a12=(a8*a10);
  a4=cos(a4);
  a14=(a4*a14);
  a14=(a6*a14);
  a12=(a12+a14);
  if (res[2]!=0) res[2][7]=a12;
  a12=arg[2]? arg[2][10] : 0;
  if (res[2]!=0) res[2][8]=a12;
  a10=(a5*a10);
  a10=(-a10);
  if (res[2]!=0) res[2][9]=a10;
  a12=(a5*a12);
  a12=(-a12);
  if (res[2]!=0) res[2][10]=a12;
  if (res[2]!=0) res[2][11]=a9;
  a12=arg[2]? arg[2][15] : 0;
  a10=(a2*a12);
  a14=arg[2]? arg[2][14] : 0;
  a15=(a16*a14);
  a15=(a0*a15);
  a10=(a10-a15);
  if (res[2]!=0) res[2][12]=a10;
  a10=(a3*a12);
  a14=(a1*a14);
  a14=(a0*a14);
  a10=(a10+a14);
  if (res[2]!=0) res[2][13]=a10;
  a10=arg[2]? arg[2][16] : 0;
  if (res[2]!=0) res[2][14]=a10;
  a12=(a5*a12);
  a12=(-a12);
  if (res[2]!=0) res[2][15]=a12;
  a10=(a5*a10);
  a10=(a5-a10);
  if (res[2]!=0) res[2][16]=a10;
  if (res[2]!=0) res[2][17]=a9;
  a10=arg[2]? arg[2][21] : 0;
  a12=(a7*a10);
  a14=arg[2]? arg[2][20] : 0;
  a15=(a13*a14);
  a15=(a6*a15);
  a12=(a12-a15);
  if (res[2]!=0) res[2][18]=a12;
  a12=(a8*a10);
  a14=(a4*a14);
  a14=(a6*a14);
  a12=(a12+a14);
  if (res[2]!=0) res[2][19]=a12;
  a12=arg[2]? arg[2][22] : 0;
  if (res[2]!=0) res[2][20]=a12;
  a10=(a5*a10);
  a10=(-a10);
  if (res[2]!=0) res[2][21]=a10;
  a12=(a5*a12);
  a12=(-a12);
  if (res[2]!=0) res[2][22]=a12;
  if (res[2]!=0) res[2][23]=a9;
  a12=arg[2]? arg[2][27] : 0;
  a10=(a2*a12);
  a14=arg[2]? arg[2][26] : 0;
  a15=(a16*a14);
  a15=(a0*a15);
  a10=(a10-a15);
  if (res[2]!=0) res[2][24]=a10;
  a10=(a3*a12);
  a14=(a1*a14);
  a14=(a0*a14);
  a10=(a10+a14);
  if (res[2]!=0) res[2][25]=a10;
  a10=arg[2]? arg[2][28] : 0;
  if (res[2]!=0) res[2][26]=a10;
  a12=(a5*a12);
  a12=(-a12);
  if (res[2]!=0) res[2][27]=a12;
  a10=(a5*a10);
  a10=(-a10);
  if (res[2]!=0) res[2][28]=a10;
  a10=1.;
  if (res[2]!=0) res[2][29]=a10;
  a12=arg[2]? arg[2][33] : 0;
  a14=(a7*a12);
  a15=arg[2]? arg[2][32] : 0;
  a11=(a13*a15);
  a11=(a6*a11);
  a14=(a14-a11);
  if (res[2]!=0) res[2][30]=a14;
  a14=(a8*a12);
  a15=(a4*a15);
  a15=(a6*a15);
  a14=(a14+a15);
  if (res[2]!=0) res[2][31]=a14;
  a14=arg[2]? arg[2][34] : 0;
  if (res[2]!=0) res[2][32]=a14;
  a12=(a5*a12);
  a12=(-a12);
  if (res[2]!=0) res[2][33]=a12;
  a14=(a5*a14);
  a14=(-a14);
  if (res[2]!=0) res[2][34]=a14;
  if (res[2]!=0) res[2][35]=a9;
  a14=arg[2]? arg[2][39] : 0;
  a12=(a2*a14);
  a15=arg[2]? arg[2][38] : 0;
  a11=(a16*a15);
  a11=(a0*a11);
  a12=(a12-a11);
  if (res[2]!=0) res[2][36]=a12;
  a12=(a3*a14);
  a15=(a1*a15);
  a15=(a0*a15);
  a12=(a12+a15);
  if (res[2]!=0) res[2][37]=a12;
  a12=arg[2]? arg[2][40] : 0;
  if (res[2]!=0) res[2][38]=a12;
  a14=(a5*a14);
  a14=(-a14);
  if (res[2]!=0) res[2][39]=a14;
  a12=(a5*a12);
  a12=(-a12);
  if (res[2]!=0) res[2][40]=a12;
  if (res[2]!=0) res[2][41]=a9;
  a12=arg[2]? arg[2][45] : 0;
  a14=(a7*a12);
  a15=arg[2]? arg[2][44] : 0;
  a11=(a13*a15);
  a11=(a6*a11);
  a14=(a14-a11);
  if (res[2]!=0) res[2][42]=a14;
  a14=(a8*a12);
  a15=(a4*a15);
  a15=(a6*a15);
  a14=(a14+a15);
  if (res[2]!=0) res[2][43]=a14;
  a14=arg[2]? arg[2][46] : 0;
  if (res[2]!=0) res[2][44]=a14;
  a12=(a5*a12);
  a12=(a5-a12);
  if (res[2]!=0) res[2][45]=a12;
  a14=(a5*a14);
  a14=(-a14);
  if (res[2]!=0) res[2][46]=a14;
  if (res[2]!=0) res[2][47]=a9;
  a14=arg[2]? arg[2][51] : 0;
  a12=(a2*a14);
  a15=arg[2]? arg[2][50] : 0;
  a11=(a16*a15);
  a11=(a0*a11);
  a12=(a12-a11);
  if (res[2]!=0) res[2][48]=a12;
  a12=(a3*a14);
  a15=(a1*a15);
  a15=(a0*a15);
  a12=(a12+a15);
  if (res[2]!=0) res[2][49]=a12;
  a12=arg[2]? arg[2][52] : 0;
  if (res[2]!=0) res[2][50]=a12;
  a14=(a5*a14);
  a14=(-a14);
  if (res[2]!=0) res[2][51]=a14;
  a12=(a5*a12);
  a12=(-a12);
  if (res[2]!=0) res[2][52]=a12;
  if (res[2]!=0) res[2][53]=a9;
  a12=arg[2]? arg[2][57] : 0;
  a14=(a7*a12);
  a15=arg[2]? arg[2][56] : 0;
  a11=(a13*a15);
  a11=(a6*a11);
  a14=(a14-a11);
  if (res[2]!=0) res[2][54]=a14;
  a14=(a8*a12);
  a15=(a4*a15);
  a15=(a6*a15);
  a14=(a14+a15);
  if (res[2]!=0) res[2][55]=a14;
  a14=arg[2]? arg[2][58] : 0;
  if (res[2]!=0) res[2][56]=a14;
  a12=(a5*a12);
  a12=(-a12);
  if (res[2]!=0) res[2][57]=a12;
  a14=(a5*a14);
  a14=(a5-a14);
  if (res[2]!=0) res[2][58]=a14;
  if (res[2]!=0) res[2][59]=a9;
  a14=arg[2]? arg[2][63] : 0;
  a2=(a2*a14);
  a12=arg[2]? arg[2][62] : 0;
  a16=(a16*a12);
  a16=(a0*a16);
  a2=(a2-a16);
  if (res[2]!=0) res[2][60]=a2;
  a3=(a3*a14);
  a1=(a1*a12);
  a0=(a0*a1);
  a3=(a3+a0);
  if (res[2]!=0) res[2][61]=a3;
  a3=arg[2]? arg[2][64] : 0;
  if (res[2]!=0) res[2][62]=a3;
  a14=(a5*a14);
  a14=(-a14);
  if (res[2]!=0) res[2][63]=a14;
  a3=(a5*a3);
  a3=(-a3);
  if (res[2]!=0) res[2][64]=a3;
  if (res[2]!=0) res[2][65]=a9;
  a9=arg[2]? arg[2][69] : 0;
  a7=(a7*a9);
  a3=arg[2]? arg[2][68] : 0;
  a13=(a13*a3);
  a13=(a6*a13);
  a7=(a7-a13);
  if (res[2]!=0) res[2][66]=a7;
  a8=(a8*a9);
  a4=(a4*a3);
  a6=(a6*a4);
  a8=(a8+a6);
  if (res[2]!=0) res[2][67]=a8;
  a8=arg[2]? arg[2][70] : 0;
  if (res[2]!=0) res[2][68]=a8;
  a9=(a5*a9);
  a9=(-a9);
  if (res[2]!=0) res[2][69]=a9;
  a5=(a5*a8);
  a5=(-a5);
  if (res[2]!=0) res[2][70]=a5;
  if (res[2]!=0) res[2][71]=a10;
  return 0;
}

CASADI_SYMBOL_EXPORT int multi_car_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int multi_car_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int multi_car_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void multi_car_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int multi_car_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void multi_car_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void multi_car_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void multi_car_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int multi_car_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int multi_car_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real multi_car_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* multi_car_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* multi_car_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* multi_car_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* multi_car_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int multi_car_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
